image: gitpod/workspace-full

tasks:
  - name: Setup NS-3
    init: |
      sudo apt update
      sudo apt install g++ python3 python3-pip cmake git qt5-default -y
      cd /workspace
      git clone https://gitlab.com/nsnam/ns-3-dev.git
      cd ns-3-dev
      ./ns3 configure --enable-examples --enable-tests
      ./ns3 build
    command: |
      echo "=== NS-3 УСТАНОВЛЕН! ==="
      echo "Для запуска симуляции:"
      echo "cd ns-3-dev"
      echo "./ns3 run scratch/ваш_файл"

vscode:
  extensions:
    - ms-vscode.cpptools
